### PR TITLE
KeysMatcher should handle contains better

### LINKED ISSUE #15: hhvm pukes on long string from print_r
related to #9 

hhvm reports the following error for Leo's test suite now:

> Fatal error: String length exceeded 2^31-2: 2147483647 in /home/travis/build/peridot-php/leo/src/Formatter/Formatter.php on line 91

Can be seen here:

https://travis-ci.org/peridot-php/leo/jobs/51746360

Seems related to print_r things, and hhvm was not originally doing this. ¯\\\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by mrkrstphr**
KeysMatcher should allow the value of a corresponding key to be null.

Fixes #15

### CODE REVIEW

**Comment by brianium** [comment]
@mrkrstphr should we just remove hhvm from the build? I personally don't care about it (at least for this matcher library), and php7 is way more fun and cool anyways right?

**Comment by mrkrstphr** [comment]
I think HHVM is a fad.

**Comment by brianium** [comment]
@mrkrstphr want to remove the hhvm badge from the README and travis build stuff with your PR? I am so over it

**Comment by mrkrstphr** [comment]
@brianium HHVM support removed

**Comment by brianium** [comment]
I will tag a new thing

**Pull request merged**
